application: ffs-cache
version: 1
runtime: python
api_version: 1

handlers:

- url: /js
  static_dir: js
  expiration: 30d

- url: /images
  static_dir: images

- url: /style_sheets
  static_dir: style_sheets
  expiration: 30d